type: rpm-ostree

remove:
  - gnome-classic-session-xsession
  - gnome-classic-session
  - gnome-terminal
  - gnome-terminal-nautilus
  - gnome-software-rpm-ostree
  - gnome-tour
  - gnome-initial-setup
  - gnome-system-monitor
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-window-list
  - gnome-shell-extension-background-logo

install:
  - gnome-pomodoro