type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo

install:
  - thunar
  - thunar-archive-plugin 
  - thunar-volman
  - xarchiver
  - gvfs-mtp
  - gvfs-gphoto2
  - gvfs-smb
  - gvfs-nfs
  - gvfs-fuse
  - gvfs-archive
  - kvantum
  - kvantum-qt5
  - xdg-user-dirs
  - wofi