type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo

install:
  - thunar
  - thunar-volman
  - thunar-archive-plugin
  - gvfs
  - gvfs-smb
  - kvantum
  - kvantum-qt5
  - yaru-theme
  - fuzzel